version: '3'

services:
  todofront:
    build: ./todo-app/front-end
    depends_on:
      - todoback
    environment:
      - REACT_APP_API_HOST=todoback
    ports:
      - 3000:3000

  todoback:
    build: ./todo-app/back-end
    ports:
      - 3001:3001

  todotests:
    depends_on:
      - todofront
      - todoback
    environment:
      - FRONT_HOST=todofront
    build: ./todo-app/tests